name: cloud-seeder
version: 0.0.0.0
category: Cloud
synopsis: A tool for interacting with AWS CloudFormation
description: |
  This package provides a DSL for creating deployment configurations, as well
  as an interpreter that reads deployment configurations in order to deploy
  application stacks to AWS CloudFormation using Amazonka.

copyright: 2017 CJ Affiliate by Conversant
license: ISC
license-file: LICENSE
author: Alexis King <lexi.lambda@gmail.com>, Michael Arnold <michaelaarnold@gmail.com>
maintainer: Alexis King <lexi.lambda@gmail.com>, Michael Arnold <michaelaarnold@gmail.com>
github: cjdev/cloud-seeder

extra-source-files:
- CHANGELOG.md
- LICENSE
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall
default-extensions:
- ApplicativeDo
- ConstraintKinds
- DefaultSignatures
- DeriveGeneric
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeOperators

library:
  dependencies:
  - amazonka >= 1.4.5
  - amazonka-cloudformation >= 1.4.5
  - amazonka-core >= 1.4.5
  - base >= 4.9.0.0 && < 5
  - deepseq >= 1.4.1.0
  - exceptions >= 0.6
  - lens
  - lens-aeson
  - monad-control >= 1.0.0.0
  - monad-logger >= 0.3.11.1
  - mtl
  - optparse-applicative >= 0.13.0.0
  - text
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - yaml
  source-dirs: library

tests:
  cloud-seeder-test-suite:
    dependencies:
    - amazonka-cloudformation
    - base
    - bytestring
    - cloud-seeder
    - deepseq
    - fast-logger
    - hspec
    - lens
    - monad-logger
    - monad-mock
    - mtl
    - text
    - transformers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
