AWSTemplateFormatVersion: '2010-09-09'
Description: Foundational resources

Parameters:
  Env:
    Type: String
    Description: The environment in which to deploy
    MinLength: 1
  Performance:
    Type: String
    Description: Peformance classification
    AllowedValues: [high, medium, low]
    Default: low

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/matryoshka-template-store/network/v0.yaml
      Parameters:
        Ec2KeyPairName: testing-20161206
  Security:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/matryoshka-template-store/security/v0.yaml
      Parameters:
        Env: !Ref Env
  DeploymentCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/matryoshka-template-store/deployment-cluster/v0.yaml
      Parameters:
        Vpc: !GetAtt Network.Outputs.VPC
        NetworkServiceSubnets: !GetAtt Network.Outputs.NetworkServiceSubnets
        Ec2KeyPairName: !GetAtt Network.Outputs.Ec2KeyPairName
        HostSecurityGroup: !GetAtt Network.Outputs.HostSecurityGroup
        NetworkServiceSecurityGroup: !GetAtt Network.Outputs.NetworkServiceSecurityGroup
        SecretsStore: !GetAtt Security.Outputs.SecretsStore
        EncryptionKey: !GetAtt Security.Outputs.EncryptionKey
        Performance: !Ref Performance

Outputs:
  VPC:
    Description: VPC ID
    Value: !GetAtt Network.Outputs.VPC
  Gateway:
    Value: !GetAtt Network.Outputs.Gateway
  RouteTable:
    Value: !GetAtt Network.Outputs.RouteTable
  NetworkServiceSubnets:
    Description: Subnets for network-facing container hosts
    Value: !GetAtt Network.Outputs.NetworkServiceSubnets
  DatabaseSubnets:
    Description: Subnets for databases
    Value: !GetAtt Network.Outputs.DatabaseSubnets
  UnreachableSubnets:
    Description: Subnets for task-only container hosts
    Value: !GetAtt Network.Outputs.UnreachableSubnets
  NetworkServiceSecurityGroup:
    Value: !GetAtt Network.Outputs.NetworkServiceSecurityGroup
  LoadBalancerSecurityGroup:
    Value: !GetAtt Network.Outputs.LoadBalancerSecurityGroup
  HostSecurityGroup:
    Value: !GetAtt Network.Outputs.HostSecurityGroup
  DatabaseSecurityGroup:
    Value: !GetAtt Network.Outputs.DatabaseSecurityGroup
  Ec2KeyPairName:
    Value: !GetAtt Network.Outputs.Ec2KeyPairName
  EncryptionKey:
    Value: !GetAtt Security.Outputs.EncryptionKey
  SecretsStore:
    Value: !GetAtt Security.Outputs.SecretsStore
  Cluster:
    Value: !GetAtt DeploymentCluster.Outputs.Cluster
  InstanceRole:
    Value: !GetAtt DeploymentCluster.Outputs.InstanceRole
  LogGroup:
    Value: !GetAtt DeploymentCluster.Outputs.LogGroup
